### ISSUE TITLE
[Compatibility Request]: dmod

### ISSUE THREAD

**Issue by Omgise** [FalsePattern/EndlessIDs#114]
### OS

Windows

### GPU

NVIDIA

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/11134482/fml-client-latest.log)

**Comment by Omgise** [comment]
The minimum set of mod crashes has been found
![image](https://user-images.githubusercontent.com/106000018/229486008-8ac8aa34-8379-48ce-8bc9-5bdbb5bbb4ac.png)
[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/11137364/fml-client-latest.log)

**Comment by vasmark1** [comment]
Hi! What exactly you do when it crashes? On my setup it works fine as well :/ 
All mods are downloaded directly form curseforge. 
![image](https://user-images.githubusercontent.com/65904048/229574313-2e7d0890-46f8-40ea-a2f2-472116eebd97.png)

**Comment by makamys** [comment]
The issue here seems to be that EIDs does not extend the stat arrays (`StatList.mineBlockStatArray`, `StatList.objectCraftStats`, `StatList.objectUseStats` and `StatList.objectBreakStats`), causing a crash when mods try to register usage stats for items with high IDs.

I may change the stat registry in D-Mod to fail safely, because *bundle usage statistics* aren't worth crashing over.

The second crash seems unrelated, it's an OpenAL crash.

**Comment by FalsePattern** [comment]
> Actually the vanilla limit for objectUseStats is 32000, and the error here happens when accessing element 5293. So StatListMixin appears to be broken and reducing the length of this array (setting it to the max block id, when it should be the max item id).

The decision of logically splitting item and block ID caps haunts me to this day.

Fix scheduled for the next release. A temporary workaround until then is setting `general->countCorrectionBits` in the config to 9 or less

**Comment by FalsePattern** [comment]
Should be fixed in alpha 8
