### ISSUE TITLE
[Compatibility Request]: Antique Atlas.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/EndlessIDs#8]
### Other mod's name

Title.

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/antique-atlas

### Other mod's license

GNU General Public License.

### Game log

[2022-07-10-5.log.gz](https://github.com/FalsePattern/EndlessIDs/files/9079982/2022-07-10-5.log.gz)
https://pastebin.com/SjpQ8FeY

### Description

Title.

**Comment by FalsePattern** [comment]
Fixed in eebb1d629eb328e7e2a80db0e6a0c9de21edda00, scheduled into Alpha 10, which will be released in a few days.

In the meantime, you can use this prerelease build: [1.4 Alpha 10 Pre 1](https://maven.falsepattern.com/com/falsepattern/endlessids-mc1.7.10/1.4.0-alpha0010-pre1/endlessids-mc1.7.10-1.4.0-alpha0010-pre1.jar)

**Comment by MagmaBro123** [comment]
Thanks

**Comment by FalsePattern** [comment]
Fixed in 1.4 Alpha 10
