### ISSUE TITLE
[Bug]: BOP with eids 1.5.0 alpha0005

### ISSUE THREAD

**Issue by swiftyflow01** [FalsePattern/EndlessIDs#97]
### OS

Windows

### GPU

NVIDIA

### Game log

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/10891382/fml-client-latest.log)

### Description

if world type is BIOMEOP game crashing after a few seconds

**Comment by Omgise** [comment]
And I was because of the explosion of Creeper, and the game crashed 
[crash-2023-03-05_21.01.16-client.txt](https://github.com/FalsePattern/EndlessIDs/files/10891876/crash-2023-03-05_21.01.16-client.txt)
[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/10891877/fml-client-latest.log)

**Comment by swiftyflow01** [comment]
#103 more information
